version: 2.0
jobs:
  build:
    machine:
      image: circleci/classic:latest
    branches:
          only:
            - master
    steps:
      - run:
          name: Install GITFTP
          command: |
            sudo apt-get update;
            sudo apt-get install git-ftp;
      - checkout
      - run:
          name: Send Via FTP
          command: 
              git-ftp ftp://${username}:${password}@${hostname} -e set ssl:verify-certificate no "mirror -v -R --exclude .git/ --exclude .circleci/ ./ ${site_name}/test-replicon quit"